# railway.toml

[build]
builder = "NIXPACKS" # Use Nixpacks for automatic language detection and build

[deploy]
startCommand = "gunicorn api.app:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT" # <-- CHANGE THIS COMMAND
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10